Response.destroy_all
Seen.destroy_all
Letter.destroy_all
Account.destroy_all

a1 = Account.create(email: 'harry@gmail.com', password: '123', icon: 'H')
a2 = Account.create(email: 'sally@gmail.com', password: '123', icon: 'S')
a3 = Account.create(email: 'pat@gmail.com', password: '123', icon: 'P')
a4 = Account.create(email: 'lea@gmail.com', password: '123', icon: 'L')
a5 = Account.create(email: 'kylo@gmail.com', password: '123', icon: 'K')
a6 = Account.create(email: 'ray@gmail.com', password: '123', icon: 'R')
a7 = Account.create(email: 'daphne@gmail.com', password: '123', icon: 'D')
a8 = Account.create(email: 'joe@gmail.com', password: '123', icon: 'J')

l1 = Letter.create(account_id: a1.id, content: "Hey guys, just wanted to say that I had a really bad day at school today and I'd love some encouragement.", icon: a1.icon)
Seen.create(account: a1, letter_id: l1.id)
l2 = Letter.create(account_id: a1.id, content: "Grey and rainy days make me sad.", icon: a1.icon)
Seen.create(account: a1, letter_id: l2.id)
l3 = Letter.create(account_id: a2.id, content: "I am sad today and I am not sure why.", icon: a2.icon)
Seen.create(account: a2, letter_id: l3.id)
l4 = Letter.create(account_id: a2.id, content: "I feel so lonely and like people don't want to be with me, what is wrong with me?", icon: a2.icon)
Seen.create(account: a2, letter_id: l4.id)
l5 = Letter.create(account_id: a3.id, content: "I failed my exam today and I feel like a complete failure.", icon: a3.icon)
Seen.create(account: a3, letter_id: l5.id)
l6 = Letter.create(account_id: a3.id, content: "I am lonely and sad today.", icon: a3.icon)
Seen.create(account: a3, letter_id: l6.id)
l7 = Letter.create(account_id: a4.id, content: "Today is stressful for me, I have to give a presentation and I don't feel confident.", icon: a4.icon)
Seen.create(account: a4, letter_id: l7.id)
l8 = Letter.create(account_id: a4.id, content: "I got in a fight with my partner today and now I feel really down.", icon: a4.icon)
Seen.create(account: a4, letter_id: l8.id)
l9 = Letter.create(account_id: a5.id, content: "I am feeling depressed and I don't feel like going to work today.", icon: a5.icon)
Seen.create(account: a5, letter_id: l9.id)
l10 = Letter.create(account_id: a5.id, content: "Today is grey and dark and I am feeling really down and bad about myself.", icon: a5.icon)
Seen.create(account: a5, letter_id: l10.id)
l11 = Letter.create(account_id: a6.id, content: "I am starting a new job today and am worried I don't know enough.", icon: a6.icon)
Seen.create(account: a6, letter_id: l11.id)
l12 = Letter.create(account_id: a6.id, content: "I was just dumped.  I feel like no one likes me.", icon: a6.icon)
Seen.create(account: a6, letter_id: l12.id)
l13 = Letter.create(account_id: a1.id, content: "I don't feel good about myself.  I wish I looked different and I wish I was smarter so people would like me more.", icon: a1.icon)
Seen.create(account: a1, letter_id: l13.id)
l14 = Letter.create(account_id: a2.id, content: "I feel like I study a lot but then I never do well at school.  I am feeling really bad about myself.", icon: a2.icon)
Seen.create(account: a2, letter_id: l14.id)
l15 = Letter.create(account_id: a1.id, content: "I didn't get the job offer I was hoping for and I'm super bummed.", icon: a1.icon)
Seen.create(account: a1, letter_id: l15.id)
l16 = Letter.create(account_id: a2.id, content: "I am feeling really sad today :(", icon: a2.icon)
Seen.create(account: a2, letter_id: l16.id)

Response.create(account_id: a8.id, letter_id: l1.id, content: "Sending hugs to you!", icon: a8.icon)
Response.create(account_id: a7.id, letter_id: l1.id, content: "Stay strong xoxo", icon: a7.icon)
Response.create(account_id: a5.id, letter_id: l1.id, content: 'Be kind to yourself.  Tomorrow will be better!', icon: a5.icon)
Response.create(account_id: a2.id, letter_id: l2.id, content: 'You are not along with these feelings. Just know that the sun always comes out and we will feel better :)', icon: a2.icon)
Response.create(account_id: a3.id, letter_id: l1.id, content: 'Sending a smile and hug your way and hoping you feel happy soon!', icon: a3.icon)
Response.create(account_id: a4.id, letter_id: l2.id, content: 'The sun will come out soon! Stay strong.', icon: a4.icon)
Response.create(account_id: a4.id, letter_id: l13.id, content: 'You are worthy and you are enough.  Be kind to yourself.', icon: a4.icon)
Response.create(account_id: a6.id, letter_id: l15.id, content: 'You are NOT a failure.  This is one backward step but you are strong and just keep moving forward.  You got this!', icon: a6.icon)
Response.create(account_id: a6.id, letter_id: l13.id, content: 'You are perfect the way you are xo', icon: a6.icon)
Response.create(account_id: a5.id, letter_id: l15.id, content: 'Stay strong, you are worthy of getting what you want and I know you will', icon: a5.icon)
